name: Debug repo structure

on: [push]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: List root directory
        run: ls -la
        
      - name: List 1st level files/folders
        run: ls -la */
